### ISSUE TITLE
Error: Unable to retrieve data

### ISSUE THREAD

**Issue by Vu1k** [ali-raheem/Aify#5]
Hi,

I completed the setup with muy OpenAI API key but i always get the message:

Error: unable to retrieve data.

I have a free account of OpenAI. May I to configure something else? upgrade my account?

Thanks

**Comment by marchausmann** [comment]
Hi,
I have exactly the same behavior.
Nothing changes trying different model of GPT3.5.
Many thanks and I wish you a good weekend.
Thanks!

**Comment by lawa42** [comment]
Same here. It doesn't even connect to openai it seems. The API usage key counter keeps on saying `never`

**Comment by ali-raheem** [comment]
Please ensure that you've got a payment on your OpenAI account as any usage now encures a fee.
Make sure the API key (starts with sk-) is in your Aify settings and saved.
Finally make sure the model you are using is one that is appropriate simplest option is gpt-3.5. And that setting is saved.

I do not believe this issue is related to Aify because it comes up so often with the above problems, but will review the settings page to see if I can make it more clear.
